### ISSUE TITLE
submission to v3 competition leaderboard failed

### ISSUE THREAD

**Issue by zdforient** [lmb-freiburg/freihand#40]
Traceback (most recent call last):
  File "/worker/worker.py", line 656, in run
    put_blob(stdout_url, stdout_file)
  File "/worker/worker.py", line 207, in put_blob
    'x-ms-version': '2018-03-28',
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='miniodis-rproxy.lisn.upsaclay.fr', port=443): Max retries exceeded with url: /py3-private/submission_stdout/a37ca71c-63fe-4cce-bebb-59eab78d448b/stdout.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20230201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230201T234153Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=f045368d6a73a2b11b76a854d1aecb2ecd8056758df656e51ae5e958a5db45bc (Caused by : [Errno 110] Connection timed out)

**Comment by zdforient** [comment]
solved after resubmission
